### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by mmargooo** [mmargooo/IO-BuildingInfo#4]

**Comment by roertbb** [comment]
Only repository owner is allowed to enable TravisCI on repository. Assigning @mmargooo for that task.

**Comment by grazik** [comment]
I think it's already implemented, hmm?
@roertbb @mmargooo

**Comment by roertbb** [comment]
I think so, but we should wait also for approval from @mmargooo

**Comment by mmargooo** [comment]
I agree
