### ISSUE TITLE
Code Quality Measurement test

### ISSUE THREAD

**Issue by roertbb** [mmargooo/IO-BuildingInfo#61]
**Description:**
- Define at least 1 measurement target connected with code quality or GQM test and choose proper metrics (at least one)
- Measure choosen metric od code/test quality

[Reference](https://docs.google.com/spreadsheets/d/e/2PACX-1vSxEKEBzcopOqfu9OHFwQkD2oDQlztfqAW0Tf_IXjElZQyKDUrzl4-oxI78NQEHZaLh1Vorl2RSyEf3/pubhtml#)

**Comment by roertbb** [comment]
Approved 👍

**Comment by mmargooo** [comment]
The effect:
https://docs.google.com/document/d/14KcNhK8FtaVTuIPNLcZo8uPY-5ZKzOZ4-IQIAAGwEa0/edit?usp=sharing
