### ISSUE TITLE
Implement Retro Actions

### ISSUE THREAD

**Issue by roertbb** [mmargooo/IO-BuildingInfo#65]
**Description:**
During last retrospection we noticed some things to improve:
- better task description [#task](https://github.com/mmargooo/IO-BuildingInfo/issues/64)
- implement retro actions as soon as possible
- adding reviewers for tasks might help us navigate better who needs code review or start group discussion about certain topic

[Reference](https://onedrive.live.com/view.aspx?resid=1E0C1083E0D1EA7A!15461&ithint=file%2cxlsx&app=Excel&authkey=!AM8vaszBle3CUyw)

**Comment by mmargooo** [comment]
I think we did a good job 🙌
Especially @roertbb with the task description :)
