### ISSUE TITLE
Plan the data structure

### ISSUE THREAD

**Issue by mmargooo** [mmargooo/IO-BuildingInfo#7]

**Comment by roertbb** [comment]
To be discussed - notes can be put [here](https://docs.google.com/document/d/1hSWrmPh0NT_0Q48qO5vc3HF6gG-uP_mrely4JWPtEWM/edit)

**Comment by grazik** [comment]
I think, that issue is resolved. We are in middle of implementing these data structure here #18

**Comment by roertbb** [comment]
Marking as resolved, further discussion in data structures implementation task
